import Head from 'next/head'
import { Poppins } from 'next/font/google'
import Navbar from '@/components/navbar/Index';
import Hero from '@/components/hero/Index';
import Main from '@/components/main/Index';
import ContactForm from '@/components/ContactForm/Index';


const popins = Poppins({
  weight: '400',
  subsets: ['latin'],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Development & Analytics - Everson</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Hero />
      <Main />
      <ContactForm />
    </>
  )
}
